<?php
/**
 * BackupJobGuestProcessingImportModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * The version of the OpenAPI document: 1.0-rev1
 * Contact: support@veeam.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BackupJobGuestProcessingImportModel Class Doc Comment
 *
 * @category Class
 * @description Guest processing settings.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BackupJobGuestProcessingImportModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BackupJobGuestProcessingImportModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'application_aware_processing' => '\OpenAPI\Client\Model\BackupApplicationAwareProcessingImportModel',
        'guest_file_system_indexing' => '\OpenAPI\Client\Model\GuestFileSystemIndexingModel',
        'guest_interaction_proxies' => '\OpenAPI\Client\Model\GuestInteractionProxiesSettingsImportModel',
        'guest_credentials' => '\OpenAPI\Client\Model\GuestOsCredentialsImportModel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'application_aware_processing' => null,
        'guest_file_system_indexing' => null,
        'guest_interaction_proxies' => null,
        'guest_credentials' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'application_aware_processing' => false,
		'guest_file_system_indexing' => false,
		'guest_interaction_proxies' => false,
		'guest_credentials' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'application_aware_processing' => 'applicationAwareProcessing',
        'guest_file_system_indexing' => 'guestFileSystemIndexing',
        'guest_interaction_proxies' => 'guestInteractionProxies',
        'guest_credentials' => 'guestCredentials'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'application_aware_processing' => 'setApplicationAwareProcessing',
        'guest_file_system_indexing' => 'setGuestFileSystemIndexing',
        'guest_interaction_proxies' => 'setGuestInteractionProxies',
        'guest_credentials' => 'setGuestCredentials'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'application_aware_processing' => 'getApplicationAwareProcessing',
        'guest_file_system_indexing' => 'getGuestFileSystemIndexing',
        'guest_interaction_proxies' => 'getGuestInteractionProxies',
        'guest_credentials' => 'getGuestCredentials'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('application_aware_processing', $data ?? [], null);
        $this->setIfExists('guest_file_system_indexing', $data ?? [], null);
        $this->setIfExists('guest_interaction_proxies', $data ?? [], null);
        $this->setIfExists('guest_credentials', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['application_aware_processing'] === null) {
            $invalidProperties[] = "'application_aware_processing' can't be null";
        }
        if ($this->container['guest_file_system_indexing'] === null) {
            $invalidProperties[] = "'guest_file_system_indexing' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets application_aware_processing
     *
     * @return \OpenAPI\Client\Model\BackupApplicationAwareProcessingImportModel
     */
    public function getApplicationAwareProcessing()
    {
        return $this->container['application_aware_processing'];
    }

    /**
     * Sets application_aware_processing
     *
     * @param \OpenAPI\Client\Model\BackupApplicationAwareProcessingImportModel $application_aware_processing application_aware_processing
     *
     * @return self
     */
    public function setApplicationAwareProcessing($application_aware_processing)
    {
        if (is_null($application_aware_processing)) {
            throw new \InvalidArgumentException('non-nullable application_aware_processing cannot be null');
        }
        $this->container['application_aware_processing'] = $application_aware_processing;

        return $this;
    }

    /**
     * Gets guest_file_system_indexing
     *
     * @return \OpenAPI\Client\Model\GuestFileSystemIndexingModel
     */
    public function getGuestFileSystemIndexing()
    {
        return $this->container['guest_file_system_indexing'];
    }

    /**
     * Sets guest_file_system_indexing
     *
     * @param \OpenAPI\Client\Model\GuestFileSystemIndexingModel $guest_file_system_indexing guest_file_system_indexing
     *
     * @return self
     */
    public function setGuestFileSystemIndexing($guest_file_system_indexing)
    {
        if (is_null($guest_file_system_indexing)) {
            throw new \InvalidArgumentException('non-nullable guest_file_system_indexing cannot be null');
        }
        $this->container['guest_file_system_indexing'] = $guest_file_system_indexing;

        return $this;
    }

    /**
     * Gets guest_interaction_proxies
     *
     * @return \OpenAPI\Client\Model\GuestInteractionProxiesSettingsImportModel|null
     */
    public function getGuestInteractionProxies()
    {
        return $this->container['guest_interaction_proxies'];
    }

    /**
     * Sets guest_interaction_proxies
     *
     * @param \OpenAPI\Client\Model\GuestInteractionProxiesSettingsImportModel|null $guest_interaction_proxies guest_interaction_proxies
     *
     * @return self
     */
    public function setGuestInteractionProxies($guest_interaction_proxies)
    {
        if (is_null($guest_interaction_proxies)) {
            throw new \InvalidArgumentException('non-nullable guest_interaction_proxies cannot be null');
        }
        $this->container['guest_interaction_proxies'] = $guest_interaction_proxies;

        return $this;
    }

    /**
     * Gets guest_credentials
     *
     * @return \OpenAPI\Client\Model\GuestOsCredentialsImportModel|null
     */
    public function getGuestCredentials()
    {
        return $this->container['guest_credentials'];
    }

    /**
     * Sets guest_credentials
     *
     * @param \OpenAPI\Client\Model\GuestOsCredentialsImportModel|null $guest_credentials guest_credentials
     *
     * @return self
     */
    public function setGuestCredentials($guest_credentials)
    {
        if (is_null($guest_credentials)) {
            throw new \InvalidArgumentException('non-nullable guest_credentials cannot be null');
        }
        $this->container['guest_credentials'] = $guest_credentials;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


