<?php
/**
 * EJobStatesFiltersOrderColumn
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * The version of the OpenAPI document: 1.0-rev1
 * Contact: support@veeam.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EJobStatesFiltersOrderColumn Class Doc Comment
 *
 * @category Class
 * @description Orders job states by the specified column.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EJobStatesFiltersOrderColumn
{
    /**
     * Possible values of this enum
     */
    public const NAME = 'Name';

    public const TYPE = 'Type';

    public const STATUS = 'Status';

    public const LAST_RUN = 'LastRun';

    public const LAST_RESULT = 'LastResult';

    public const NEXT_RUN = 'NextRun';

    public const DESCRIPTION = 'Description';

    public const REPOSITORY_ID = 'RepositoryId';

    public const OBJECTS_COUNT = 'ObjectsCount';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NAME,
            self::TYPE,
            self::STATUS,
            self::LAST_RUN,
            self::LAST_RESULT,
            self::NEXT_RUN,
            self::DESCRIPTION,
            self::REPOSITORY_ID,
            self::OBJECTS_COUNT
        ];
    }
}


