<?php
/**
 * ERepositoryType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * The version of the OpenAPI document: 1.0-rev1
 * Contact: support@veeam.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ERepositoryType Class Doc Comment
 *
 * @category Class
 * @description Repository type.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ERepositoryType
{
    /**
     * Possible values of this enum
     */
    public const WIN_LOCAL = 'WinLocal';

    public const LINUX_LOCAL = 'LinuxLocal';

    public const SMB = 'Smb';

    public const NFS = 'Nfs';

    public const AZURE_BLOB = 'AzureBlob';

    public const AZURE_ARCHIVE = 'AzureArchive';

    public const AMAZON_S3 = 'AmazonS3';

    public const AMAZON_S3_GLACIER = 'AmazonS3Glacier';

    public const S3_COMPATIBLE = 'S3Compatible';

    public const GOOGLE_CLOUD = 'GoogleCloud';

    public const IBM_CLOUD = 'IBMCloud';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WIN_LOCAL,
            self::LINUX_LOCAL,
            self::SMB,
            self::NFS,
            self::AZURE_BLOB,
            self::AZURE_ARCHIVE,
            self::AMAZON_S3,
            self::AMAZON_S3_GLACIER,
            self::S3_COMPATIBLE,
            self::GOOGLE_CLOUD,
            self::IBM_CLOUD
        ];
    }
}


