<?php
/**
 * EVmwareInventoryType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * The version of the OpenAPI document: 1.0-rev1
 * Contact: support@veeam.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EVmwareInventoryType Class Doc Comment
 *
 * @category Class
 * @description Type of the VMware vSphere object.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EVmwareInventoryType
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const VIRTUAL_MACHINE = 'VirtualMachine';

    public const V_CENTER_SERVER = 'vCenterServer';

    public const DATACENTER = 'Datacenter';

    public const CLUSTER = 'Cluster';

    public const HOST = 'Host';

    public const RESOURCE_POOL = 'ResourcePool';

    public const FOLDER = 'Folder';

    public const DATASTORE = 'Datastore';

    public const DATASTORE_CLUSTER = 'DatastoreCluster';

    public const STORAGE_POLICY = 'StoragePolicy';

    public const TEMPLATE = 'Template';

    public const COMPUTE_RESOURCE = 'ComputeResource';

    public const VIRTUAL_APP = 'VirtualApp';

    public const TAG = 'Tag';

    public const CATEGORY = 'Category';

    public const MULTITAG = 'Multitag';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::VIRTUAL_MACHINE,
            self::V_CENTER_SERVER,
            self::DATACENTER,
            self::CLUSTER,
            self::HOST,
            self::RESOURCE_POOL,
            self::FOLDER,
            self::DATASTORE,
            self::DATASTORE_CLUSTER,
            self::STORAGE_POLICY,
            self::TEMPLATE,
            self::COMPUTE_RESOURCE,
            self::VIRTUAL_APP,
            self::TAG,
            self::CATEGORY,
            self::MULTITAG
        ];
    }
}


