<?php
/**
 * MountServerSettingsImportSpec
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * The version of the OpenAPI document: 1.0-rev1
 * Contact: support@veeam.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MountServerSettingsImportSpec Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MountServerSettingsImportSpec implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MountServerSettingsImportSpec';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'mount_server_name' => 'string',
        'write_cache_folder' => 'string',
        'v_power_nfs_enabled' => 'bool',
        'v_power_nfs_port_settings' => '\OpenAPI\Client\Model\VPowerNFSPortSettingsModel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'mount_server_name' => null,
        'write_cache_folder' => null,
        'v_power_nfs_enabled' => null,
        'v_power_nfs_port_settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'mount_server_name' => false,
		'write_cache_folder' => false,
		'v_power_nfs_enabled' => false,
		'v_power_nfs_port_settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'mount_server_name' => 'mountServerName',
        'write_cache_folder' => 'writeCacheFolder',
        'v_power_nfs_enabled' => 'vPowerNFSEnabled',
        'v_power_nfs_port_settings' => 'vPowerNFSPortSettings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'mount_server_name' => 'setMountServerName',
        'write_cache_folder' => 'setWriteCacheFolder',
        'v_power_nfs_enabled' => 'setVPowerNfsEnabled',
        'v_power_nfs_port_settings' => 'setVPowerNfsPortSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'mount_server_name' => 'getMountServerName',
        'write_cache_folder' => 'getWriteCacheFolder',
        'v_power_nfs_enabled' => 'getVPowerNfsEnabled',
        'v_power_nfs_port_settings' => 'getVPowerNfsPortSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('mount_server_name', $data ?? [], null);
        $this->setIfExists('write_cache_folder', $data ?? [], null);
        $this->setIfExists('v_power_nfs_enabled', $data ?? [], null);
        $this->setIfExists('v_power_nfs_port_settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['mount_server_name'] === null) {
            $invalidProperties[] = "'mount_server_name' can't be null";
        }
        if ($this->container['write_cache_folder'] === null) {
            $invalidProperties[] = "'write_cache_folder' can't be null";
        }
        if ($this->container['v_power_nfs_enabled'] === null) {
            $invalidProperties[] = "'v_power_nfs_enabled' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets mount_server_name
     *
     * @return string
     */
    public function getMountServerName()
    {
        return $this->container['mount_server_name'];
    }

    /**
     * Sets mount_server_name
     *
     * @param string $mount_server_name Name of the mount server.
     *
     * @return self
     */
    public function setMountServerName($mount_server_name)
    {
        if (is_null($mount_server_name)) {
            throw new \InvalidArgumentException('non-nullable mount_server_name cannot be null');
        }
        $this->container['mount_server_name'] = $mount_server_name;

        return $this;
    }

    /**
     * Gets write_cache_folder
     *
     * @return string
     */
    public function getWriteCacheFolder()
    {
        return $this->container['write_cache_folder'];
    }

    /**
     * Sets write_cache_folder
     *
     * @param string $write_cache_folder Path to the folder used for writing cache during mount operations.
     *
     * @return self
     */
    public function setWriteCacheFolder($write_cache_folder)
    {
        if (is_null($write_cache_folder)) {
            throw new \InvalidArgumentException('non-nullable write_cache_folder cannot be null');
        }
        $this->container['write_cache_folder'] = $write_cache_folder;

        return $this;
    }

    /**
     * Gets v_power_nfs_enabled
     *
     * @return bool
     */
    public function getVPowerNfsEnabled()
    {
        return $this->container['v_power_nfs_enabled'];
    }

    /**
     * Sets v_power_nfs_enabled
     *
     * @param bool $v_power_nfs_enabled If *true*, the vPower NFS Service is enabled on the mount server.
     *
     * @return self
     */
    public function setVPowerNfsEnabled($v_power_nfs_enabled)
    {
        if (is_null($v_power_nfs_enabled)) {
            throw new \InvalidArgumentException('non-nullable v_power_nfs_enabled cannot be null');
        }
        $this->container['v_power_nfs_enabled'] = $v_power_nfs_enabled;

        return $this;
    }

    /**
     * Gets v_power_nfs_port_settings
     *
     * @return \OpenAPI\Client\Model\VPowerNFSPortSettingsModel|null
     */
    public function getVPowerNfsPortSettings()
    {
        return $this->container['v_power_nfs_port_settings'];
    }

    /**
     * Sets v_power_nfs_port_settings
     *
     * @param \OpenAPI\Client\Model\VPowerNFSPortSettingsModel|null $v_power_nfs_port_settings v_power_nfs_port_settings
     *
     * @return self
     */
    public function setVPowerNfsPortSettings($v_power_nfs_port_settings)
    {
        if (is_null($v_power_nfs_port_settings)) {
            throw new \InvalidArgumentException('non-nullable v_power_nfs_port_settings cannot be null');
        }
        $this->container['v_power_nfs_port_settings'] = $v_power_nfs_port_settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


