<?php
/**
 * ObjectRestorePointsFilters
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * The version of the OpenAPI document: 1.0-rev1
 * Contact: support@veeam.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ObjectRestorePointsFilters Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ObjectRestorePointsFilters implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ObjectRestorePointsFilters';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'skip' => 'int',
        'limit' => 'int',
        'order_column' => '\OpenAPI\Client\Model\EObjectRestorePointsFiltersOrderColumn',
        'order_asc' => 'bool',
        'created_after_filter' => '\DateTime',
        'created_before_filter' => '\DateTime',
        'name_filter' => 'string',
        'platform_name_filter' => '\OpenAPI\Client\Model\EPlatformType',
        'platform_id_filter' => 'string',
        'backup_id_filter' => 'string',
        'backup_object_id_filter' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'skip' => 'int32',
        'limit' => 'int32',
        'order_column' => null,
        'order_asc' => null,
        'created_after_filter' => 'date-time',
        'created_before_filter' => 'date-time',
        'name_filter' => null,
        'platform_name_filter' => null,
        'platform_id_filter' => 'uuid',
        'backup_id_filter' => 'uuid',
        'backup_object_id_filter' => 'uuid'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'skip' => false,
		'limit' => false,
		'order_column' => false,
		'order_asc' => false,
		'created_after_filter' => false,
		'created_before_filter' => false,
		'name_filter' => false,
		'platform_name_filter' => false,
		'platform_id_filter' => false,
		'backup_id_filter' => false,
		'backup_object_id_filter' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'skip' => 'skip',
        'limit' => 'limit',
        'order_column' => 'orderColumn',
        'order_asc' => 'orderAsc',
        'created_after_filter' => 'createdAfterFilter',
        'created_before_filter' => 'createdBeforeFilter',
        'name_filter' => 'nameFilter',
        'platform_name_filter' => 'platformNameFilter',
        'platform_id_filter' => 'platformIdFilter',
        'backup_id_filter' => 'backupIdFilter',
        'backup_object_id_filter' => 'backupObjectIdFilter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'skip' => 'setSkip',
        'limit' => 'setLimit',
        'order_column' => 'setOrderColumn',
        'order_asc' => 'setOrderAsc',
        'created_after_filter' => 'setCreatedAfterFilter',
        'created_before_filter' => 'setCreatedBeforeFilter',
        'name_filter' => 'setNameFilter',
        'platform_name_filter' => 'setPlatformNameFilter',
        'platform_id_filter' => 'setPlatformIdFilter',
        'backup_id_filter' => 'setBackupIdFilter',
        'backup_object_id_filter' => 'setBackupObjectIdFilter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'skip' => 'getSkip',
        'limit' => 'getLimit',
        'order_column' => 'getOrderColumn',
        'order_asc' => 'getOrderAsc',
        'created_after_filter' => 'getCreatedAfterFilter',
        'created_before_filter' => 'getCreatedBeforeFilter',
        'name_filter' => 'getNameFilter',
        'platform_name_filter' => 'getPlatformNameFilter',
        'platform_id_filter' => 'getPlatformIdFilter',
        'backup_id_filter' => 'getBackupIdFilter',
        'backup_object_id_filter' => 'getBackupObjectIdFilter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('skip', $data ?? [], null);
        $this->setIfExists('limit', $data ?? [], null);
        $this->setIfExists('order_column', $data ?? [], null);
        $this->setIfExists('order_asc', $data ?? [], null);
        $this->setIfExists('created_after_filter', $data ?? [], null);
        $this->setIfExists('created_before_filter', $data ?? [], null);
        $this->setIfExists('name_filter', $data ?? [], null);
        $this->setIfExists('platform_name_filter', $data ?? [], null);
        $this->setIfExists('platform_id_filter', $data ?? [], null);
        $this->setIfExists('backup_id_filter', $data ?? [], null);
        $this->setIfExists('backup_object_id_filter', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets skip
     *
     * @return int|null
     */
    public function getSkip()
    {
        return $this->container['skip'];
    }

    /**
     * Sets skip
     *
     * @param int|null $skip skip
     *
     * @return self
     */
    public function setSkip($skip)
    {
        if (is_null($skip)) {
            throw new \InvalidArgumentException('non-nullable skip cannot be null');
        }
        $this->container['skip'] = $skip;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int|null $limit limit
     *
     * @return self
     */
    public function setLimit($limit)
    {
        if (is_null($limit)) {
            throw new \InvalidArgumentException('non-nullable limit cannot be null');
        }
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets order_column
     *
     * @return \OpenAPI\Client\Model\EObjectRestorePointsFiltersOrderColumn|null
     */
    public function getOrderColumn()
    {
        return $this->container['order_column'];
    }

    /**
     * Sets order_column
     *
     * @param \OpenAPI\Client\Model\EObjectRestorePointsFiltersOrderColumn|null $order_column order_column
     *
     * @return self
     */
    public function setOrderColumn($order_column)
    {
        if (is_null($order_column)) {
            throw new \InvalidArgumentException('non-nullable order_column cannot be null');
        }
        $this->container['order_column'] = $order_column;

        return $this;
    }

    /**
     * Gets order_asc
     *
     * @return bool|null
     */
    public function getOrderAsc()
    {
        return $this->container['order_asc'];
    }

    /**
     * Sets order_asc
     *
     * @param bool|null $order_asc order_asc
     *
     * @return self
     */
    public function setOrderAsc($order_asc)
    {
        if (is_null($order_asc)) {
            throw new \InvalidArgumentException('non-nullable order_asc cannot be null');
        }
        $this->container['order_asc'] = $order_asc;

        return $this;
    }

    /**
     * Gets created_after_filter
     *
     * @return \DateTime|null
     */
    public function getCreatedAfterFilter()
    {
        return $this->container['created_after_filter'];
    }

    /**
     * Sets created_after_filter
     *
     * @param \DateTime|null $created_after_filter created_after_filter
     *
     * @return self
     */
    public function setCreatedAfterFilter($created_after_filter)
    {
        if (is_null($created_after_filter)) {
            throw new \InvalidArgumentException('non-nullable created_after_filter cannot be null');
        }
        $this->container['created_after_filter'] = $created_after_filter;

        return $this;
    }

    /**
     * Gets created_before_filter
     *
     * @return \DateTime|null
     */
    public function getCreatedBeforeFilter()
    {
        return $this->container['created_before_filter'];
    }

    /**
     * Sets created_before_filter
     *
     * @param \DateTime|null $created_before_filter created_before_filter
     *
     * @return self
     */
    public function setCreatedBeforeFilter($created_before_filter)
    {
        if (is_null($created_before_filter)) {
            throw new \InvalidArgumentException('non-nullable created_before_filter cannot be null');
        }
        $this->container['created_before_filter'] = $created_before_filter;

        return $this;
    }

    /**
     * Gets name_filter
     *
     * @return string|null
     */
    public function getNameFilter()
    {
        return $this->container['name_filter'];
    }

    /**
     * Sets name_filter
     *
     * @param string|null $name_filter name_filter
     *
     * @return self
     */
    public function setNameFilter($name_filter)
    {
        if (is_null($name_filter)) {
            throw new \InvalidArgumentException('non-nullable name_filter cannot be null');
        }
        $this->container['name_filter'] = $name_filter;

        return $this;
    }

    /**
     * Gets platform_name_filter
     *
     * @return \OpenAPI\Client\Model\EPlatformType|null
     */
    public function getPlatformNameFilter()
    {
        return $this->container['platform_name_filter'];
    }

    /**
     * Sets platform_name_filter
     *
     * @param \OpenAPI\Client\Model\EPlatformType|null $platform_name_filter platform_name_filter
     *
     * @return self
     */
    public function setPlatformNameFilter($platform_name_filter)
    {
        if (is_null($platform_name_filter)) {
            throw new \InvalidArgumentException('non-nullable platform_name_filter cannot be null');
        }
        $this->container['platform_name_filter'] = $platform_name_filter;

        return $this;
    }

    /**
     * Gets platform_id_filter
     *
     * @return string|null
     */
    public function getPlatformIdFilter()
    {
        return $this->container['platform_id_filter'];
    }

    /**
     * Sets platform_id_filter
     *
     * @param string|null $platform_id_filter platform_id_filter
     *
     * @return self
     */
    public function setPlatformIdFilter($platform_id_filter)
    {
        if (is_null($platform_id_filter)) {
            throw new \InvalidArgumentException('non-nullable platform_id_filter cannot be null');
        }
        $this->container['platform_id_filter'] = $platform_id_filter;

        return $this;
    }

    /**
     * Gets backup_id_filter
     *
     * @return string|null
     */
    public function getBackupIdFilter()
    {
        return $this->container['backup_id_filter'];
    }

    /**
     * Sets backup_id_filter
     *
     * @param string|null $backup_id_filter backup_id_filter
     *
     * @return self
     */
    public function setBackupIdFilter($backup_id_filter)
    {
        if (is_null($backup_id_filter)) {
            throw new \InvalidArgumentException('non-nullable backup_id_filter cannot be null');
        }
        $this->container['backup_id_filter'] = $backup_id_filter;

        return $this;
    }

    /**
     * Gets backup_object_id_filter
     *
     * @return string|null
     */
    public function getBackupObjectIdFilter()
    {
        return $this->container['backup_object_id_filter'];
    }

    /**
     * Sets backup_object_id_filter
     *
     * @param string|null $backup_object_id_filter backup_object_id_filter
     *
     * @return self
     */
    public function setBackupObjectIdFilter($backup_object_id_filter)
    {
        if (is_null($backup_object_id_filter)) {
            throw new \InvalidArgumentException('non-nullable backup_object_id_filter cannot be null');
        }
        $this->container['backup_object_id_filter'] = $backup_object_id_filter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


