<?php
/**
 * RepositoryImportSpecCollection
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * The version of the OpenAPI document: 1.0-rev1
 * Contact: support@veeam.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RepositoryImportSpecCollection Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RepositoryImportSpecCollection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RepositoryImportSpecCollection';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'windows_local_repositories' => '\OpenAPI\Client\Model\WindowsLocalStorageImportSpec[]',
        'linux_local_repositories' => '\OpenAPI\Client\Model\LinuxLocalStorageImportSpec[]',
        'smb_repositories' => '\OpenAPI\Client\Model\SmbStorageImportSpec[]',
        'nfs_repositories' => '\OpenAPI\Client\Model\NfsStorageImportSpec[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'windows_local_repositories' => null,
        'linux_local_repositories' => null,
        'smb_repositories' => null,
        'nfs_repositories' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'windows_local_repositories' => false,
		'linux_local_repositories' => false,
		'smb_repositories' => false,
		'nfs_repositories' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'windows_local_repositories' => 'WindowsLocalRepositories',
        'linux_local_repositories' => 'LinuxLocalRepositories',
        'smb_repositories' => 'SmbRepositories',
        'nfs_repositories' => 'NfsRepositories'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'windows_local_repositories' => 'setWindowsLocalRepositories',
        'linux_local_repositories' => 'setLinuxLocalRepositories',
        'smb_repositories' => 'setSmbRepositories',
        'nfs_repositories' => 'setNfsRepositories'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'windows_local_repositories' => 'getWindowsLocalRepositories',
        'linux_local_repositories' => 'getLinuxLocalRepositories',
        'smb_repositories' => 'getSmbRepositories',
        'nfs_repositories' => 'getNfsRepositories'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('windows_local_repositories', $data ?? [], null);
        $this->setIfExists('linux_local_repositories', $data ?? [], null);
        $this->setIfExists('smb_repositories', $data ?? [], null);
        $this->setIfExists('nfs_repositories', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets windows_local_repositories
     *
     * @return \OpenAPI\Client\Model\WindowsLocalStorageImportSpec[]|null
     */
    public function getWindowsLocalRepositories()
    {
        return $this->container['windows_local_repositories'];
    }

    /**
     * Sets windows_local_repositories
     *
     * @param \OpenAPI\Client\Model\WindowsLocalStorageImportSpec[]|null $windows_local_repositories Array of windows local storages.
     *
     * @return self
     */
    public function setWindowsLocalRepositories($windows_local_repositories)
    {
        if (is_null($windows_local_repositories)) {
            throw new \InvalidArgumentException('non-nullable windows_local_repositories cannot be null');
        }


        $this->container['windows_local_repositories'] = $windows_local_repositories;

        return $this;
    }

    /**
     * Gets linux_local_repositories
     *
     * @return \OpenAPI\Client\Model\LinuxLocalStorageImportSpec[]|null
     */
    public function getLinuxLocalRepositories()
    {
        return $this->container['linux_local_repositories'];
    }

    /**
     * Sets linux_local_repositories
     *
     * @param \OpenAPI\Client\Model\LinuxLocalStorageImportSpec[]|null $linux_local_repositories Array of linux local storages.
     *
     * @return self
     */
    public function setLinuxLocalRepositories($linux_local_repositories)
    {
        if (is_null($linux_local_repositories)) {
            throw new \InvalidArgumentException('non-nullable linux_local_repositories cannot be null');
        }


        $this->container['linux_local_repositories'] = $linux_local_repositories;

        return $this;
    }

    /**
     * Gets smb_repositories
     *
     * @return \OpenAPI\Client\Model\SmbStorageImportSpec[]|null
     */
    public function getSmbRepositories()
    {
        return $this->container['smb_repositories'];
    }

    /**
     * Sets smb_repositories
     *
     * @param \OpenAPI\Client\Model\SmbStorageImportSpec[]|null $smb_repositories Array of network attached storages.
     *
     * @return self
     */
    public function setSmbRepositories($smb_repositories)
    {
        if (is_null($smb_repositories)) {
            throw new \InvalidArgumentException('non-nullable smb_repositories cannot be null');
        }


        $this->container['smb_repositories'] = $smb_repositories;

        return $this;
    }

    /**
     * Gets nfs_repositories
     *
     * @return \OpenAPI\Client\Model\NfsStorageImportSpec[]|null
     */
    public function getNfsRepositories()
    {
        return $this->container['nfs_repositories'];
    }

    /**
     * Sets nfs_repositories
     *
     * @param \OpenAPI\Client\Model\NfsStorageImportSpec[]|null $nfs_repositories Array of network attached storages.
     *
     * @return self
     */
    public function setNfsRepositories($nfs_repositories)
    {
        if (is_null($nfs_repositories)) {
            throw new \InvalidArgumentException('non-nullable nfs_repositories cannot be null');
        }


        $this->container['nfs_repositories'] = $nfs_repositories;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


